version: '3'

services:
  db:
    image: postgres:13
    container_name: db
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - network
  web:
    build: .
    command: guinicorn desafio.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/desafio
    expose:
      - 8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    networks:
      network:
        aliases:
          - web
  nginx:
    build: ./nginx
    ports: 
      - 8000:80
    depends_on:
      - web
    networks:
      network:
        aliases:
          - nginx
    

networks:
  network:
    driver: bridge

volumes:
  postgres: