# Generated by Django 4.1.3 on 2022-11-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='greeting',
            field=models.CharField(default='Hello', max_length=254, unique=True),
        ),
    ]
