# Generated by Django 4.1.3 on 2022-11-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0002_alter_hello_greeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hello',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
